name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: '1.22.1'

permissions: read-all
jobs:
  go-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Build
        run: go build -tags sdl .
